services:
  - type: web
    name: agrofix-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: JWT_SECRET
        value: your-secret-key
